AWSTemplateFormatVersion: "2010-09-09"
Description: Create all of the resources neccesary for the aboutmyhometown.com website. This does no include a few resources like registered domains and ACM certificates.
Parameters:
  DomainName:
    Type: String
    Description: The DNS name for the website
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  AcmCertificateArn:
    Type: String
    Description: the Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
    AllowedPattern: "arn:aws:acm:.*"

Resources:
  PrimaryVPC:
    Type: "AWS::EC2::VPC"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsSupport: true
      InstanceTenancy: default
      EnableDnsHostnames: true
      Tags: []

  aboutmyhometownCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      DistributionConfig:
        Comment: "The primary distribution for the web application"
        DefaultRootObject: index.html
        Origins:
          - Id: !Join ["", ["www.", !Ref "DomainName", ".s3.amazonaws.com"]]
            DomainName:
              !Join ["", ["www.", !Ref "DomainName", ".s3.amazonaws.com"]]
            OriginAccessControlId: !Ref aboutmyhometownCloudFrontOriginAccessControl
            ConnectionTimeout: 10
            ConnectionAttempts: 3
            S3OriginConfig:
              OriginAccessIdentity: ""
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref AcmCertificateArn
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          Compress: true
          TrustedKeyGroups: []
          FunctionAssociations: []
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          LambdaFunctionAssociations: []
          SmoothStreaming: false
          TargetOriginId:
            !Join ["", ["www.", !Ref "DomainName", ".s3.amazonaws.com"]]
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId:
            Ref: aboutmyhometownCloudFrontCachePolicy
        Enabled: true
        Aliases:
          - !Ref "DomainName"
          - !Join ["", ["www.", !Ref "DomainName"]]
        IPV6Enabled: true
        HttpVersion: http2and3
    DependsOn:
      - aboutmyhometownS3Bucket

  aboutmyhometownCloudFrontCachePolicy:
    Type: "AWS::CloudFront::CachePolicy"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      CachePolicyConfig:
        Comment: Policy with caching enabled. Supports Gzip and Brotli compression.
        MinTTL: 1
        MaxTTL: 3.1536E7
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
        DefaultTTL: 86400
        Name: aboutmyhometownCachingOptimized

  aboutmyhometownCloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      OriginAccessControlConfig:
        Description: The origin access control for the CloudFront distribution
        Name: aboutmyhometownOACConfig
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  aboutmyhometownS3Bucket:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Join ["", ["www.", !Ref "DomainName"]]
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  aboutmyhometownS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Bucket:
        Ref: aboutmyhometownS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Resource: !Join ["", ["arn:aws:s3:::www.", !Ref "DomainName", /*]]
            Action: "s3:GetObject"
            Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${aboutmyhometownCloudFrontDistribution}"
            Sid: AllowCloudFrontServicePrincipalReadOnly

  aboutmyhometownLambdaS3Bucket:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Join ["", ["www.", !Ref "DomainName"]]
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  aboutmyhometownLambdaS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      Bucket:
        Ref: aboutmyhometownLambdaS3Bucket
      PolicyDocument:
        Version: 2012-10-17

  aboutmyhometownRoute53HostedZone:
    Type: "AWS::Route53::HostedZone"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: HostedZone created by Route53 Registrar
      Name: !Join ["", [!Ref "DomainName", .]]
    DependsOn:
      - aboutmyhometownCloudFrontDistribution

  aboutmyhometownRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      HostedZoneName: !Join ["", [!Ref "DomainName", .]]
      RecordSets:
        - Name: !Join ["", ["www.", !Ref "DomainName"]]
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [aboutmyhometownCloudFrontDistribution, DomainName]
        - Name: !Ref "DomainName"
          Type: A
          AliasTarget:
            HostedZoneId: Z05567953GIEW3X3P58TA
            DNSName: !Join ["", ["www.", !Ref "DomainName"]]

  aboutmyhometownMySQLDB:
    Type: "AWS::RDS::DBInstance"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Retain"
    Properties:
      StorageEncrypted: true
      PreferredBackupWindow: "04:12-04:42"
      DBParameterGroupName: "default.mysql8.0"
      NetworkType: "IPV4"
      Engine: "mysql"
      LicenseModel: "general-public-license"
      EngineVersion: "8.0.35"
      StorageType: "gp2"
      DBInstanceClass: "db.t3.micro"
      OptionGroupName: "default:mysql-8-0"
      PreferredMaintenanceWindow: "mon:03:39-mon:04:09"
      AutoMinorVersionUpgrade: true
      DBInstanceIdentifier: "aboutmyhometown-mysql-db"
      AllocatedStorage: "20"
      MasterUsername: "admin"
      MasterUserPassword: "iDontKnowHowToHideThisPassword741"
      MaxAllocatedStorage: 1000
      BackupRetentionPeriod: 1
