Metadata:
  TemplateId: >-
    arn:aws:cloudformation:us-east-2:211125302470:generatedTemplate/c4203234-2d30-4fbb-b952-0d56e7be35f1
  'AWS::CloudFormation::Designer':
    1e31e534-9bb6-4f76-a058-e16a53c94e6f:
      size:
        width: 150
        height: 150
      position:
        x: 70
        'y': 300
      z: 1
      embeds: []
    c05d39ec-5a2b-481c-8978-1907f88f523c:
      size:
        width: 150
        height: 150
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    dbd3440f-e7b0-4809-8749-ad23c4d81f23:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 300
      z: 1
      embeds: []
    c368da38-e0fc-485e-9cc5-50eb30c9b6e6:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 410
      z: 1
      embeds: []
    a1008612-9f94-4644-bdbe-51ad2325bea0:
      size:
        width: 60
        height: 60
      position:
        x: 300
        'y': 300
      z: 1
      embeds: []
    a812908a-178f-4b47-8bca-a1f67162bf95:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 50
      z: 1
      embeds: []
    bdb0db6f-6197-44ab-9baa-c1ae0e9fde55:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 210
      z: 1
      embeds: []
      dependson:
        - dbd3440f-e7b0-4809-8749-ad23c4d81f23
        - a1008612-9f94-4644-bdbe-51ad2325bea0
    57cb561f-1216-442d-8318-b911b28726f2:
      source:
        id: bdb0db6f-6197-44ab-9baa-c1ae0e9fde55
      target:
        id: dbd3440f-e7b0-4809-8749-ad23c4d81f23
      z: 11
    9ab2e672-c81b-4cce-8a75-e187ddeeacb2:
      source:
        id: bdb0db6f-6197-44ab-9baa-c1ae0e9fde55
      target:
        id: a1008612-9f94-4644-bdbe-51ad2325bea0
      z: 12
Resources:
  PrimaryCloudFront:
    UpdateReplacePolicy: Retain
    Type: 'AWS::CloudFront::Distribution'
    DeletionPolicy: Retain
    Properties:
      DistributionConfig:
        Logging:
          IncludeCookies: false
          Bucket: ''
          Prefix: ''
        Comment: ''
        DefaultRootObject: index.html
        Origins:
          - ConnectionTimeout: 10
            OriginAccessControlId: ''
            ConnectionAttempts: 3
            OriginCustomHeaders: []
            DomainName: www.aboutmyhometown.com.s3-website.us-east-2.amazonaws.com
            OriginShield:
              Enabled: false
            OriginPath: ''
            Id: www.aboutmyhometown.com.s3.us-east-2.amazonaws.com
            CustomOriginConfig:
              OriginKeepaliveTimeout: 5
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - SSLv3
                - TLSv1
                - TLSv1.1
                - TLSv1.2
              HTTPSPort: 443
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
          AcmCertificateArn: >-
            arn:aws:acm:us-east-1:211125302470:certificate/eab948a5-95f3-4cb9-aeb8-af6b9e549934
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          Compress: true
          TrustedKeyGroups: []
          FunctionAssociations: []
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          LambdaFunctionAssociations: []
          SmoothStreaming: false
          TargetOriginId: www.aboutmyhometown.com.s3.us-east-2.amazonaws.com
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId:
            Ref: CloudFrontCachePolicy
          TrustedSigners: []
          FieldLevelEncryptionId: ''
        Staging: false
        CustomErrorResponses: []
        ContinuousDeploymentPolicyId: ''
        OriginGroups:
          Quantity: 0
          Items: []
        Enabled: true
        Aliases:
          - aboutmyhometown.com
          - www.aboutmyhometown.com
        IPV6Enabled: true
        WebACLId: ''
        HttpVersion: http2and3
        Restrictions:
          GeoRestriction:
            Locations: []
            RestrictionType: none
        CacheBehaviors: []
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bdb0db6f-6197-44ab-9baa-c1ae0e9fde55
    DependsOn:
      - aboutmyhometownS3Bucket
      - >-
        Route53ResolverResolverRuleAssociation
  CloudFrontCachePolicy:
    UpdateReplacePolicy: Retain
    Type: 'AWS::CloudFront::CachePolicy'
    DeletionPolicy: Retain
    Properties:
      CachePolicyConfig:
        Comment: Policy with caching enabled. Supports Gzip and Brotli compression.
        MinTTL: 1
        MaxTTL: 3.1536E7
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
        DefaultTTL: 86400
        Name: Managed-CachingOptimized
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a812908a-178f-4b47-8bca-a1f67162bf95
  Route53ResolverResolverRuleAssociation:
    UpdateReplacePolicy: Retain
    Type: 'AWS::Route53Resolver::ResolverRuleAssociation'
    DeletionPolicy: Retain
    Properties:
      VPCId:
        Ref: PrimaryEC2VPC
      ResolverRuleId: rslvr-autodefined-rr-internet-resolver
      Name: System Rule Association
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a1008612-9f94-4644-bdbe-51ad2325bea0
  aboutmyhometownS3Bucket:
    UpdateReplacePolicy: Retain
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: www.aboutmyhometown.com
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dbd3440f-e7b0-4809-8749-ad23c4d81f23
  PrimaryEC2VPC:
    UpdateReplacePolicy: Retain
    Type: 'AWS::EC2::VPC'
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsSupport: true
      InstanceTenancy: default
      EnableDnsHostnames: true
      Tags: []
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c05d39ec-5a2b-481c-8978-1907f88f523c
  aboutmyhometownS3BucketPolicy:
    UpdateReplacePolicy: Retain
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: Retain
    Properties:
      Bucket:
        Ref: aboutmyhometownS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Resource: 'arn:aws:s3:::www.aboutmyhometown.com/*'
            Action: 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Sid: AllowPublicReadAccess
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c368da38-e0fc-485e-9cc5-50eb30c9b6e6
  Route53HostedZone:
    UpdateReplacePolicy: Retain
    Type: 'AWS::Route53::HostedZone'
    DeletionPolicy: Retain
    Properties:
      VPCs: []
      HostedZoneConfig:
        Comment: HostedZone created by Route53 Registrar
      Name: aboutmyhometown.com.
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1e31e534-9bb6-4f76-a058-e16a53c94e6f
